version: "3.8"

services:
  app:
    build:
      args:
        user: juanfarias
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: kinghost
    working_dir: /var/www/
    restart: always
    volumes:
      - ./:/var/www/
    networks:
      - api-filmes

  web:
    image: nginx:alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./.docker/nginx/:/etc/nginx/conf.d/
      - ./:/var/www/
    networks:
      - api-filmes

  mariadb:
    image: mariadb:10.3
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - api-filmes

networks:
  api-filmes:
    driver: bridge

volumes:
    db_data:
